name: "Next version"
description: "Get the next version number in a Git repo"

inputs:
  current-version:
    description: "The current version string"
    required: true

  revision-prefix:
    description: "The prefix for the revision number, defaults to 'r'"
    default: "r"

outputs:
  next-version:
    description: "A version string with a unique revision number"

runs:
  using: "node20"
  main: "dist/index.js"
