name: PR Merge Comment
description: Adds a comment to a merged PR with the version number.

inputs:
  version:
    description: Version to use in the PR comment
    required: true

runs:
  using: composite
  steps:
    - name: Comment on merged PR
      uses: actions/github-script@v7
      with:
        script: |
          const { prMergeComment } = require('./main.js');
          const version = "${{ inputs.version }}";
          await prMergeComment(github, context, version);
