name: PR Merge Comment
description: Adds a comment to a merged PR with the version number.

inputs:
  version:
    description: Version to use in the PR comment
    required: true
  sha:
    description: Optional Git SHA (useful for testing)
    required: false

runs:
  using: composite
  steps:
    - name: Comment on merged PR
      uses: actions/github-script@v7
      with:
        script: |
          const { prMergeComment } = require('./pr-merge-comment/main.js');
          const version = "${{ inputs.version }}";
          const sha = "${{ inputs.sha }}";
          await prMergeComment(github, context, { version, sha });
