name: PR Merge Comment
description: Adds a comment to a merged PR with the version number.

inputs:
  version:
    description: Version to use in the PR comment
    required: true
  sha:
    description: Optional Git SHA (useful for testing)
    required: false

runs:
  using: node20
  main: index.js
