name: Test action

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all tags
          fetch-depth: 0

      - name: Install dependencies
        run: cd next-version; npm ci

      - name: Tests
        run: cd next-version; npm test

      - name: Next version
        id: next-version
        uses: symless/actions/next-version@master
        with:
          current-version: 1.2.3

      - name: Print result
        run: echo "${{ steps.next-version.outputs.next-version }}"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.next-version.outputs.next-version }}
          release_name: ${{ steps.next-version.outputs.next-version }}
          commitish: master
          draft: false
          prerelease: true
