name: Test action

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all tags
          fetch-depth: 0

      - name: Test action
        id: test
        uses: ./
        with:
          current-version: 1.0.4

      - name: Print result
        run: echo "${{ steps.test.outputs.next-version }}"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.test.outputs.next-version }}
          release_name: ${{ steps.test.outputs.next-version }}
          commitish: master
          draft: false
          prerelease: true
